# Generated by Django 5.1.7 on 2025-03-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
