# Generated by Django 5.1.7 on 2025-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email_delete_customuser'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(to='students.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
